### ISSUE TITLE
[feat]格式化输出的Json以适配大部分本地化工具的问题

### ISSUE THREAD

**Issue by dyxang** [F-loat/vscode-plugin-html-i18n#1]
我看到这个工具输出的json格式是这样的：
```json
  {
    "origin": "Hello",
    "local": "你好"
  },
...
```
这种格式貌似是这个插件独有的，但是基本上很多本地化工具（比如Crowdin和transifex）他们基本上json翻译文件是这样的：
```json
//翻译前
  {
    "Hello": "Hello"
  },
//翻译后
  {
    "Hello": "你好"
  },
```
如果要将该插件修改成导出的json能导入通用本地化工具的话，我是否应该把这些地方
https://github.com/F-loat/vscode-plugin-html-i18n/blob/d5208441c8e816c159b5c67cbe57e00aa9f68ea6/src/parse.ts#L10

https://github.com/F-loat/vscode-plugin-html-i18n/blob/d5208441c8e816c159b5c67cbe57e00aa9f68ea6/src/render.ts#L24

更改为
`return { "text": "text" }; `和` set(tree, item.paths, texts[index].text); `就可以了呢？
我是小白，不知道这样做是否正确，谢谢！

**Comment by F-loat** [comment]
0.2.0 版本的 JSON 已修改为通用格式，同时新增了翻译 API 的配置项 https://github.com/F-loat/vscode-plugin-html-i18n/commit/bd6792159689d1d4d4f60e3a5064c683637f4dca

**Comment by F-loat** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/16759376/189523448-d4a9013b-2a85-42a8-ba76-47259b844ce4.png">
